# Site settings
title: James Swaro
email: james.swaro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my homepage. Welcome. I'll be adding links to my projects,
  papers and thesis at some point.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: 
github_username:  jswaro

# Build settings
markdown: kramdown
